# Generated by Django 3.2.3 on 2022-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_item_itemkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemKey',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
